### PR TITLE
Marcinj/token

### PR DESCRIPTION
**Pull request by MarcinJuraszek**
This change allows the user to specify API_SECRET to be used when making calls to Nightscout APIs.

This is needed for anybody who has set the default permission on their Nightscout instance to denied, making un-authenticated API calls return 401 Unathorized.

I tested it on my own Karoo 2 and Nightscout instance.

Here's the UI in an android emulator:

image

### CODE REVIEW

**Comment by MarcinJuraszek** [comment]
Once again, sorry about my previous PR which was missing the XML file for the main activity changes.

**Comment by nothinganprisas** [comment]
Hi MarcinJuraszek,
I am a new Karoo 2 owner so I installed the latest version (1.0.10) of the inflite apk to monitor my glucose levels but it seems I have nightscout setup (currently in Google cloud) in a way that prevents the apk to get connected, I always get a 401 error code. 
On the other hand this is a bit weird, because I also use my garmin 820 edge on which I have a couple of IQ plugins already installed and both deliver information in their respective data fields using the very same url and no token... 
So I am a bit lost because I do not understand what can be going on with the hammerhead; the thing is that I love this device but if I cannot make it work, I'm afraid I will have to return it and go for the garmin 1030+... could you help me somehow? do you know if the calls made to nightscout record any log/json so that I may look into it?
Thank you so much in advance

**Comment by haspden** [comment]
Do you have an active data connection via WiFi or 3G on the device ?

Do you use an API access key than you need to be able to look at Nightscout if using a computer?

Would you mind sharing your Nightscout URL for testing ? You can email this to me if you prefer at ***@***.***

Thanks

Henry



Get TypeApp for Android

**Comment by haspden** [comment]
Merged

**Comment by nothinganprisas** [comment]
Hi Henry, Thank you for assisting me on this. I've finally fixed it by setting up my nightscout allowing readable connections, so now I may see the glucose figures in my K2. Now I will manage to figure out how to get them using a token...  do you know if nightscout API is the very same irrespective of the platform nightscout is deployed (google cloud, azure, heroku, etc)? not sure how to compose the call to include the token, I've tried with some examples found on nightscout but thy didn't work. Or maybe I have to fine tune my nightscout server and add any user/role with the appropriate premissions.. anyway, I will play with all options available. Thank you again for your time, much appreciated. BestAlberto

    En lunes, 27 de marzo de 2023, 09:57:52 CEST, haspden ***@***.***> escribió:  
 
 

Do you have an active data connection via WiFi or 3G on the device ?

Do you use an API access key than you need to be able to look at Nightscout if using a computer?

Would you mind sharing your Nightscout URL for testing ? You can email this to me if you prefer at ***@***.***

Thanks

Henry



Get TypeApp for Android

**Comment by haspden** [comment]
Hi Alberto

The Latest release (v1.1.1) now allows API Secrets for you via an additional text Input field.

There is docs on how to authenticate API calls using the token on the Nightscout docs for other applications

Hope this helps






Get TypeApp for Android

**Comment by nothinganprisas** [comment]
Hi Henry,Just released! I'll test it asap and revert. 
By the way, not sure if we, as users, are allowed to propose apk enhancements or whether this is the right place to do it or not... as I said, I've been using Garmin until now and I would like to make a suggestion to optimize the way the info is being depicted.Best,
Alberto


    En martes, 28 de marzo de 2023, 12:46:30 CEST, haspden ***@***.***> escribió:  
 
 

Hi Alberto

The Latest release (v1.1.1) now allows API Secrets for you via an additional text Input field.

There is docs on how to authenticate API calls using the token on the Nightscout docs for other applications

Hope this helps






Get TypeApp for Android

**Comment by haspden** [comment]
Please feel free to send suggestions or raise as an "issue" in GitHub

More the merrier happy to try work on improving things for everybody involved here where we can 👍

Cheers

**Comment by nothinganprisas** [comment]
> Please feel free to send suggestions or raise as an "issue" in GitHub More the merrier happy to try work on improving things for everybody involved here where we can 👍 Cheers
> […](#)
> On 28 Mar 2023, 12:09, at 12:09, nothinganprisas ***@***.***> wrote: Hi Henry,Just released! I'll test it asap and revert. By the way, not sure if we, as users, are allowed to propose apk enhancements or whether this is the right place to do it or not... as I said, I've been using Garmin until now and I would like to make a suggestion to optimize the way the info is being depicted.Best, Alberto En martes, 28 de marzo de 2023, 12:46:30 CEST, haspden ***@***.***> escribió: Hi Alberto The Latest release (v1.1.1) now allows API Secrets for you via an additional text Input field. There is docs on how to authenticate API calls using the token on the Nightscout docs for other applications Hope this helps Get TypeApp for Android On 28 Mar 2023, 10:49, at 10:49, nothinganprisas ***@***.***> wrote: >Hi Henry, Thank you for assisting me on this. I've finally fixed it by >setting up my nightscout allowing readable connections, so now I may >see the glucose figures in my K2. Now I will manage to figure out how >to get them using a token...  do you know if nightscout API is the very >same irrespective of the platform nightscout is deployed (google cloud, >azure, heroku, etc)? not sure how to compose the call to include the >token, I've tried with some examples found on nightscout but thy didn't >work. Or maybe I have to fine tune my nightscout server and add any >user/role with the appropriate premissions.. anyway, I will play with >all options available. Thank you again for your time, much >appreciated. BestAlberto > >En lunes, 27 de marzo de 2023, 09:57:52 CEST, haspden ***@***.***> >escribió: > > > >Do you have an active data connection via WiFi or 3G on the device ? > >Do you use an API access key than you need to be able to look at >Nightscout if using a computer? > >Would you mind sharing your Nightscout URL for testing ? You can email >this to me if you prefer at ***@***.*** > >Thanks > >Henry > > > >Get TypeApp for Android > > > >On 26 Mar 2023, 23:17, at 23:17, nothinganprisas ***@***.***> wrote: >>Hi MarcinJuraszek, >>I am a new Karoo 2 owner so I installed the latest version (1.0.10) of >>the inflite apk to monitor my glucose levels but it seems I have >>nightscout setup (currently in Google cloud) in a way that prevents >the >>apk to get connected, I always get a 401 error code. >>On the other hand this is a bit weird, because I also use my garmin >820 >>edge on which I have a couple of IQ plugins already installed and both >>deliver information in their respective data fields using the very >same >>url and no token... >>So I am a bit lost because I do not understand what can be going on >>with the hammerhead; the thing is that I love this device but if I >>cannot make it work, I'm afraid I will have to return it and go for >the >>garmin 1030+... could you help me somehow? do you know if the calls >>made to nightscout record any log/json so that I may look into it? >>Thank you so much in advance >> >>-- >>Reply to this email directly or view it on GitHub: >>[#7 (comment)](https://github.com/haspden/INFLITE-TYPE-ONE-Hammerhead-CGM/pull/7#issuecomment-1484239649) >>You are receiving this because you are subscribed to this thread. >> >>Message ID: >>***@***.***> > >— >Reply to this email directly, view it on GitHub, or unsubscribe. >You are receiving this because you commented.Message ID: ***@***.***> > > >-- >Reply to this email directly or view it on GitHub: >[#7 (comment)](https://github.com/haspden/INFLITE-TYPE-ONE-Hammerhead-CGM/pull/7#issuecomment-1486540965) >You are receiving this because you modified the open/close state. > >Message ID: >***@***.***> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***> -- Reply to this email directly or view it on GitHub: [#7 (comment)](https://github.com/haspden/INFLITE-TYPE-ONE-Hammerhead-CGM/pull/7#issuecomment-1486654514) You are receiving this because you modified the open/close state. Message ID: ***@***.

**Comment by nothinganprisas** [comment]
Hi,
Tested on my Karoo 2 and working flawlessly! A big THANK YOU to all of you!

**Comment by haspden** [comment]
Amazing!!! For reference, INFLITE TYPE ONE is the UKs first and only cycling running and triathlon teams to be made up entirely of athletes living racing and thriving with type one diabetes.

This application has been developed to help and support those riding with the team, or spread awareness of the team so this is me doing my shameless plug !!!

IG

https://www.instagram.com/inflitetypeone/

Facebook

https://www.facebook.com/inflitetypeone

Strava

https://www.strava.com/clubs/1050005

Zwift Club

https://www.zwift.com/eu/clubs/1e8a838c-3534-4b32-b929-febf9c0caa71/join

Zwift Power

https://zwiftpower.com/team.php?id=17952&sid=30553ec135ef1327e8e32f39e92ebc4b

Web

https://inflitetypeone.cc

Cheers,

Henry



Get TypeApp for Android

**Pull request merged**
